package app.constants;

public enum Cities {
	ALBA, ARAD, ARGES,
	BACAU, BIHOR, BISTRITA_NASAUD, BOTOSANI, BRAILA, BRASOV, BUZAU, BUCURESTI,
	CALARASI, CARAS_SEVERIN, CLUJ, CONSTANTA, COVASNA,
	DIMBOVITA, DOLJ,
	GALATI, GIURGIU, GORJ,
	HARGHITA, HUNEDOARA,
	IALOMITA, IASI, ILFOV,
	MARAMURES, MEHEDINTI, MURES,
	NEAMT,
	OLT,
	PRAHOVA,
	SALAJ, SATU_MARE, SIBIU, SUCEAVA,
	TELEORMAN, TIMIS, TULCEA,
	VASLUI, VILCEA, VRANCEA,
}
